spring:
  datasource:
    hikari:
      connection-timeout: 10000
    url: ${datasource}?createDatabaseIfNotExist = true
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  jwt:
    header: Authorization
    secret: ${jwt.secret}
    token-validity-in-seconds : 3600
    refresh-secret: ${jwt.secret.refresh}

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

server:
  port: 8080