name: Foregg Migration
run-name: Running
on:
  push:
    branches:
      - production
      - 'releases/**'

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: foreggmigrationbucket
  AWS_CODE_DEPLOY_APPLICATION: ForeggMigrationCICD
  AWS_CODE_DEPLOY_GROUP: Foregg-Migration-CD-Group

jobs:
  build-with-gradle:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        ref: production
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build the project
      run: ./gradlew clean build -x test
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.FOREGG_MIGRATION_ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.FOREGG_MIGRATION_SECRETKEY }}
    - name: Upload to S3
      run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://${{ env.AWS_S3_BUCKET }}/cicdtest/${{ github.sha }}.zip --source .
    - name: Deploy to EC2
      run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} --s3-location bucket=${{ env.AWS_S3_BUCKET }},key=cicdtest/${{ github.sha }}.zip,bundleType=zip
